import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';
import * as apiSidebar from './docs/api/sidebar';

const sidebars: SidebarsConfig = {
  docSidebar: [
    {
      type: 'autogenerated',
      dirName: 'docs',
    },
  ],
  apiSidebar: apiSidebar.default,
};

export default sidebars;
